# Generated by Django 5.2.4 on 2025-10-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planmate', '0002_subject_created_by_alter_teacher_managed_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scheduled_subjects',
            field=models.ManyToManyField(blank=True, related_name='scheduled_by_students', to='Planmate.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='Planmate.subject'),
        ),
    ]
